version: '3'
services:
  server: &server
    build:
      context: ./
    restart: always
    depends_on:
      - db
    volumes:
      - staticfiles:/app/staticfiles/
    environment:
      - DJANGO_SECRET_KEY=youshoulddefinetelychangethistosomethingelseandtakecare
      - FIELD_ENCRYPTION_KEY=qjq4ObsXMqiqQyfKgD-jjEGm4ep8RaHKGRg4ohGCi1A=
      - DJANGO_TIME_ZONE=Europe/Vilnius
      - DJANGO_DB_URL=postgres://postgres@db:5432/postgres
    ports:
      - 80:80
      - 443:443
  guacd:
    image: linuxserver/guacd
    restart: always
  db:
    image: postgres:10.4-alpine
    restart: always
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  staticfiles:
  postgres-data:
