version: '3'
services:
  server: &server
    build:
      context: ./
      dockerfile: Dockerfile-server
    volumes:
      - staticfiles:/home/app/server/staticfiles/
    environment:
      - DJANGO_SECRET_KEY=youshoulddefinetelychangethistosomethingelseandtakecare
      - DJANGO_TIME_ZONE=Europe/Vilnius
      - DJANGO_ALLOWED_HOSTS=server,
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    depends_on:
      - server
    volumes:
      - staticfiles:/home/app/server/staticfiles/
    ports:
      - 8080:8080
  guacd:
    image: linuxserver/guacd
    restart: always
    ports:
      - 4822:4822

volumes:
  staticfiles:
