site_name: NetBox
theme: readthedocs
repo_url: https://github.com/paidem/guacozy

pages:
  - Introduction: 'index.md'
  - Installation:
      - Installing Guacozy: 'installation/index.md'
      - 1. docker-compose: 'installation/docker-compose.md'
      - 2. SSL: 'installation/ssl.md'
      - 4. LDAP: 'installation/ldap.md'
      - 3. additional guacd: 'installation/additional-guacd.md'
  - Core:
      - Folders: 'core/folders.md'
      - Connections: 'core/connections.md'
      - Tickets: 'core/tickets.md'
      - Static Credentials: 'core/static-credentials.md'
      - Named Credentials: 'core/named-credentials.md'
      - Permissions: 'core/permissions.md'
  - Features:
      - Shared access: 'features/ticket-sharing.md'
      - Audit log: 'features/audit-log.md'
  - Development:
      - Environment setup: 'development/environment-setup.md'